### PR TITLE
Update initialize_bouncer_middleware.stub

### PR DESCRIPTION
**Pull request by brunolipe-a**
### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

There is a typescript build problem in this code. I don't know if this is the best way to do it, but it is resolves the problem.

image

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Julien-R44** [comment]
Hey, thanks for the PR, but I think you are just missing this provider in your `adonisrc.ts` file : 

```ts
  providers: [
     // ... others providers
    () => import('@adonisjs/core/providers/edge_provider'),
  ],
  ```

**Comment by brunolipe-a** [comment]
So we should add that to configure command?

**Comment by Julien-R44** [comment]
Oh wait sorry. Indeed a fix is needed, because maybe you are not using Edge. And so, `ctx.view` type will be `unknown`. But using a `as any` will not be the best way. We gonna think about it

**Comment by thetutlage** [comment]
If you are not using edge  You just delete that line from the created middleware.

There is no need to modify the stub.

**Comment by brunolipe-a** [comment]
So this should be explicit in the docs, right? So that we don't have this same issue in the future.

**Comment by thetutlage** [comment]
Yeah, we can update the docs to mention to remove this line if you are not using Edge.

**Comment by Julien-R44** [comment]
What about conditionally add this line in the middleware only if `edge.js` is installed on the user's application? I mean, in `configure.ts` we could have a check like that
It should be easy to do

**Comment by RomainLanz** [comment]
> What about conditionally add this line in the middleware only if `edge.js` is installed on the user's application? I mean, in `configure.ts` we could have a check like that It should be easy to do

If we do that, people will install `Edge.js` afterward will have an issue. I believe we are better off documenting it and leave it to the user.

**Comment by Julien-R44** [comment]
i was thinking about that : if Edge is not installed, we add the middleware with commented code. that way, if people need to install edge afterward, they can simply uncomment the code

```ts

    /**
     * Uncomment if you need Edge helpers
     */
   // if ('view' in ctx) {
   //  ctx.view.share(ctx.bouncer.edgeHelpers)
   // }
```

Having to manually update the bouncer middleware seems a bit boring. But it's not the end of the world either

**Comment by thetutlage** [comment]
I think, we are trying to serve individuals who do not want to understand the surrounding ecosystem of the framework. They will always struggle to use the framework.

- You have a piece of code which gives a compiler error
- Then within the docs, the same piece of code is documented with the reasoning "Why it exists" and "When to remove it".

But you ignore the docs, do not understand the error in the first place and start with an issue, then its a problem with you and not with anything else.

Also, I do not want to make these configure commands complicated like in v5 and then create a mess for ourselves in order to maintain them.

**Comment by thetutlage** [comment]
Documented. https://github.com/adonisjs/v6-docs/commit/0912db42d5165fc2efa6c2a998100a6faf8239f6

https://docs.adonisjs.com/guides/authorization#the-initialize-bouncer-middleware

**Pull request closed without merging**
